modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"

[[mods]]
    modId="hotkeybind"
    version="1.5.2"
    displayName="Command Macros"
    description="Bind commands and macros to keys."
    authors="Gabrielsim, Amiya"

[[dependencies.hotkeybind]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.hotkeybind]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="CLIENT"
